### ISSUE TITLE
ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by PrimoWW** [yrcong/STTran#26]
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    from lib.object_detector import detector
  File "/home/xxx/project/STTran3/lib/object_detector.py", line 11, in <module>
    from fasterRCNN.lib.model.faster_rcnn.resnet import resnet
  File "/home/xxx/project/STTran3/fasterRCNN/lib/model/faster_rcnn/resnet.py", line 6, in <module>
    from fasterRCNN.lib.model.faster_rcnn.faster_rcnn import _fasterRCNN
  File "/home/xxx/project/STTran3/fasterRCNN/lib/model/faster_rcnn/faster_rcnn.py", line 10, in <module>
    from fasterRCNN.lib.model.rpn.rpn import _RPN
  File "/home/xxx/project/STTran3/fasterRCNN/lib/model/rpn/rpn.py", line 8, in <module>
    from .proposal_layer import _ProposalLayer
  File "/home/xxx/project/STTran3/fasterRCNN/lib/model/rpn/proposal_layer.py", line 21, in <module>
    from fasterRCNN.lib.model.roi_layers import nms
  File "/home/xxx/project/STTran3/fasterRCNN/lib/model/roi_layers/__init__.py", line 3, in <module>
    from .nms import nms
  File "/home/xxx/project/STTran3/fasterRCNN/lib/model/roi_layers/nms.py", line 3, in <module>
    from fasterRCNN.lib.model import _C
ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory

你好，我打算复现项目的时候遇到了这个错误，这个错误是否和cuda的版本有关？
我用nvidia-smi的命令看了下我的cuda是11.4，然后试了多个pytorch的版本都遇到了这个问题。这个问题是因为cuda版本不对导致的吗

**Comment by entalent** [comment]
If you use pre-built PyTorch (installed via pip or conda), the cuda version (i.e. the version of nvcc compiler) need to be consistent with the cuda version used by PyTorch (the version shown by `torch.version.cuda`).
If you use a higher version of PyTorch, you can try to replace the fasterRCNN folder with the  of [pytorch-1.0 branch](https://github.com/jwyang/faster-rcnn.pytorch/tree/pytorch-1.0) of faster-rcnn.pytorch. The following files are modified by the author of STTran and need to be kept:
- fasterRCNN/lib/model/utils/config.py
- fasterRCNN/lib/faster_rcnn/faster_rcnn.py
- fasterRCNN/lib/model/rpn/rpn.py
