### ISSUE TITLE
ImportError: cannot import name '_C' from 'fasterRCNN.lib.model' (/home/k/kajal/STTran/fasterRCNN/lib/model/__init__.py)

### ISSUE THREAD

**Issue by kajal15003** [yrcong/STTran#50]
Please help

**Comment by yrcong** [comment]
I guess you didn't compile the C++ code (correctly). Please run the setup.py.

Btw, I think the code only supports the cuda version<11.1.

**Comment by AlphaGoooo** [comment]
Do you solve this problem? My cuda version is 11.8 and I also met this problem.

**Comment by yrcong** [comment]
> Do you solve this problem? My cuda version is 11.8 and I also met this problem.

I think the exclusive solution is using cuda<=11.0 and GPU<2080Ti

**Comment by kajal15003** [comment]
I have downgraded the cuda version. But it is still showing the same error

**Comment by yrcong** [comment]
Have you compiled the code again after downgrading the cuda version?

**Comment by kajal15003** [comment]
Yes, it is showing the below one in the output
running build_ext

**Comment by CL2LC** [comment]
我也遇到了这个问题，断断续续搞了三天进行了很多操作，不确定哪步起的作用，大概逻辑是：
1. 作者提供了fasterRCNN/lib/build文件，里面明明有我们要的‘_C’文件，并且报错中的fasterRCNN/lib/model/里也有却找不到； 都说版本不对，我设置了很多搭配：成功的是CUDA10.0+pytorch1.1，由于我是Ubuntu22.04安装CUDA10.0相当费劲，经历了GCC降级等，最后我这边整成了多版本CUDA（因为之前别的程序使用高版本，我怕捡了芝麻丢了西瓜）
2. 改完版本以后能找到了，但是报错‘_C’文件里少东西，了解了一下是因为‘_C’文件是这个作者提供的，我们应该自己运行一下，于是我去到fasterRCNN/lib目录运行python setup.py build_ext --inplace，生成自己的‘_C’文件在对应位置，解决了就

**Comment by lianglili** [comment]
/home/anaconda3/envs/ssparser/bin/python3.7 /data/lll/SSParser/train_agqa_relation.py -mode sgdet -datasize large -data_path /data/lll/SSParser/data/agqa_decomp/ 
Traceback (most recent call last):
  File "/data/lll/SSParser/train_agqa_relation.py", line 15, in <module>
    from lib.object_detector_agqa_relation import detector
  File "/data/lll/SSParser/lib/object_detector_agqa_relation.py", line 13, in <module>
    from fasterRCNN.lib.model.faster_rcnn.resnet_plus import resnet
  File "/data/lll/SSParser/fasterRCNN/lib/model/faster_rcnn/resnet_plus.py", line 6, in <module>
    from .faster_rcnn_plus import _fasterRCNN
  File "/data/lll/SSParser/fasterRCNN/lib/model/faster_rcnn/faster_rcnn_plus.py", line 11, in <module>
    from ..rpn.rpn import _RPN
  File "/data/lll/SSParser/fasterRCNN/lib/model/rpn/rpn.py", line 9, in <module>
    from .proposal_layer import _ProposalLayer
  File "/data/lll/SSParser/fasterRCNN/lib/model/rpn/proposal_layer.py", line 21, in <module>
    from ..roi_layers import nms
  File "/data/lll/SSParser/fasterRCNN/lib/model/roi_layers/__init__.py", line 3, in <module>
    from .nms import nms
  File "/data/lll/SSParser/fasterRCNN/lib/model/roi_layers/nms.py", line 3, in <module>
    from ...model import _C
ImportError: dynamic module does not define module export function (PyInit__C)
